layout_spectrum: 0.2158336
typography_spectrum: 0.8904071
color:
  saturation: 0.05004596
  lightness: 0.7707397
  brandStrength: 0.2573414
  rhythmicContrast: 0.07741036
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
name: VinodVarma
